apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: reconciler
  namespace: flux-system
spec:
  interval: 5m0s
  path: fluxcd/clusters/home/
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-git