{{- range $key, $value := .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ $key }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ $value }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/{{ $key }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master
  persistentVolumeReclaimPolicy: Delete
{{- end }}