apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
spec:
  interval: 5m 
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      version: 7.7.0
  values:
    global:
      edition: ce
      hosts:
        domain: gitlab.tenk.local
      ingress:
        configureCertmanager: false
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
      kas:
        enabled: false
      gitaly:
        enabled: false
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    redis:
      metrics:
        enabled: false
      master:
        persistence:
          storageClass: manual
          size: 10Gi
    postgresql:
      metrics:
        enabled: false
      primary:
        storageClass: manual
        size: 50Gi
    gitlab-runner:
      install: false
    minio:
      persistence:
        storageClass: manual
        size: 50Gi
    registry:
      enabled: false
    gitlab:
      toolbox:
        enabled: false
      migrations:
        enabled: false
      webservice:
        enabled: false
      sidekiq:
        enabled: false
      gitlab-shell:
        enabled: false