apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
spec:
  interval: 5m 
  chart:
    spec:
      chart: gitlab
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      version: 7.7.0
  values:
    global:
      edition: ce
      hosts:
        domain: gitlab.tenk.local
    certmanager:
      install: false
    nginx-ingress:
      enabled: false
    prometheus:
      install: false