apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m 
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.9.0
  values:
    fullnameOverride: "ingress-nginx"
    controller:
      kind: DaemonSet
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      config:
        enable-underscores-in-headers: "true"
        use-forwarded-headers: "true"
        proxy-body-size: "20m"
      electionID: ingress
      ingressClass: nginx
      replicaCount: 1
      minAvailable: 1
      healthCheckPath: "/healthz"
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
    defaultBackend:
      enabled: false
